In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")

In [3]:
df.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [4]:
df.tail()

Gender        Age    Height      Weight family_history_with_overweight  \
2106  Female  20.976842  1.710730  131.408528                            yes   
2107  Female  21.982942  1.748584  133.742943                            yes   
2108  Female  22.524036  1.752206  133.689352                            yes   
2109  Female  24.361936  1.739450  133.346641                            yes   
2110  Female  23.664709  1.738836  133.472641                            yes   

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O SCC       FAF       TUE  \
2106  yes   3.0  3.0  Sometimes    no  1.728139  no  1.676269  0.906247   
2107  yes   3.0  3.0  Sometimes    no  2.005130  no  1.341390  0.599270   
2108  yes   3.0  3.0  Sometimes    no  2.054193  no  1.414209  0.646288   
2109  yes   3.0  3.0  Sometimes    no  2.852339  no  1.139107  0.586035   
2110  yes   3.0  3.0  Sometimes    no  2.863513  no  1.026452  0.714137   

           CALC                 MTRANS        NObeyesdad  
2106  Sometimes  Public_Transportation  Obesity_Type_III  
2107  Sometimes  Public_Transportation  Obesity_Type_III  
2108  Sometimes  Public_Transportation  Obesity_Type_III  
2109  Sometimes  Public_Transportation  Obesity_Type_III  
2110  Sometimes  Public_Transportation  Obesity_Type_III

In [5]:
df.shape

(2111, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Gender                          2111 non-null   object 
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object 
 12  FAF                             21

In [7]:
df.describe()

Age       Height       Weight         FCVC          NCP  \
count  2111.000000  2111.000000  2111.000000  2111.000000  2111.000000   
mean     24.312600     1.701677    86.586058     2.419043     2.685628   
std       6.345968     0.093305    26.191172     0.533927     0.778039   
min      14.000000     1.450000    39.000000     1.000000     1.000000   
25%      19.947192     1.630000    65.473343     2.000000     2.658738   
50%      22.777890     1.700499    83.000000     2.385502     3.000000   
75%      26.000000     1.768464   107.430682     3.000000     3.000000   
max      61.000000     1.980000   173.000000     3.000000     4.000000   

              CH2O          FAF          TUE  
count  2111.000000  2111.000000  2111.000000  
mean      2.008011     1.010298     0.657866  
std       0.612953     0.850592     0.608927  
min       1.000000     0.000000     0.000000  
25%       1.584812     0.124505     0.000000  
50%       2.000000     1.000000     0.625350  
75%       2.477420     1.666678     1.000000  
max       3.000000     3.000000     2.000000

In [8]:
df.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [9]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [10]:
num_cols = df.select_dtypes(exclude='object')
cat_cols = df.select_dtypes(include='object')

In [11]:
num_cols.head()

Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE
0  21.0    1.62    64.0   2.0  3.0   2.0  0.0  1.0
1  21.0    1.52    56.0   3.0  3.0   3.0  3.0  0.0
2  23.0    1.80    77.0   2.0  3.0   2.0  2.0  1.0
3  27.0    1.80    87.0   3.0  3.0   2.0  2.0  0.0
4  22.0    1.78    89.8   2.0  1.0   2.0  0.0  0.0

In [12]:
cat_cols.head()

Gender family_history_with_overweight FAVC       CAEC SMOKE  SCC  \
0  Female                            yes   no  Sometimes    no   no   
1  Female                            yes   no  Sometimes   yes  yes   
2    Male                            yes   no  Sometimes    no   no   
3    Male                             no   no  Sometimes    no   no   
4    Male                             no   no  Sometimes    no   no   

         CALC                 MTRANS           NObeyesdad  
0          no  Public_Transportation        Normal_Weight  
1   Sometimes  Public_Transportation        Normal_Weight  
2  Frequently  Public_Transportation        Normal_Weight  
3  Frequently                Walking   Overweight_Level_I  
4   Sometimes  Public_Transportation  Overweight_Level_II

sns.pairplot(data=df)

sns.heatmap(data = num_cols)

for i in df.columns:
    try:
        plt.figure(figsize = (8, 2))
        sns.scatterplot(x = df[i],y = df['NObeyesdad'])
        plt.xlabel(i)
        plt.ylabel('NObeyesdad')
        plt.show()
    
    except:
        pass

for i in df.columns:
    try:
        plt.figure(figsize = (12,3))
        sns.countplot(x = df[i])
        plt.xlabel(i)
        plt.show()
    
    except:
        pass

In [13]:
df['NObeyesdad'].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

In [14]:
mapping = {'Insufficient_Weight':0, 'Normal_Weight': 1, 'Obesity_Type_I': 2,
 'Obesity_Type_II': 3, 'Obesity_Type_III': 4, 'Overweight_Level_I': 5, 'Overweight_Level_II': 6}


In [15]:
df['NObeyesdad'] = df['NObeyesdad'].map(mapping)

In [16]:
df['NObeyesdad'].unique()

array([1, 5, 6, 2, 0, 3, 4], dtype=int64)

for col in num_cols:
    print(col)
    print('Skew :', round(df[col].skew(), 2))
    plt.figure(figsize = (15, 4))
    plt.subplot(1, 2, 1)
    df[col].hist(grid=False)
    plt.ylabel('count')
    plt.subplot(1, 2, 2)
    sns.boxplot(x=df[col])
    plt.show()

In [17]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [18]:
features = ['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS']
target = 'NObeyesdad'


In [19]:

X = df[features]
y = df[target]

In [20]:
num_cols = X.select_dtypes(exclude='object')
cat_cols = X.select_dtypes(include='object')

In [21]:
num_cols.shape,cat_cols.shape

((2111, 8), (2111, 8))

In [22]:
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import OneHotEncoder

# Initialize the Normalizer
scaler = Normalizer()

# Fit and transform the data
num_cols = scaler.fit_transform(num_cols)

# Initialize the OneHotEncoder
encoder = OneHotEncoder()

# Fit and transform the data
cat_cols = encoder.fit_transform(cat_cols).toarray()

In [23]:
num_cols.shape,cat_cols.shape

((2111, 8), (2111, 23))

In [24]:
X = np.concatenate((num_cols,cat_cols),axis=1)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

decisiontreeclassifier = DecisionTreeClassifier(max_depth = 7, min_samples_leaf = 3, min_samples_split = 2)
randomforestclassifier = RandomForestClassifier(max_depth = 15, min_samples_split = 2, n_estimators = 300)
gradientboostingclassifier = GradientBoostingClassifier(learning_rate = 0.1, max_depth = 7, n_estimators =100)

In [27]:
# fitting the models with train data
decisiontreeclassifier.fit(X_train,y_train)
randomforestclassifier.fit(X_train,y_train)
gradientboostingclassifier.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=7)

In [31]:
# predit the models with test data
y_pred1 = decisiontreeclassifier.predict(X_test)
y_pred2 = randomforestclassifier.predict(X_test)
y_pred3 = gradientboostingclassifier.predict(X_test)

In [50]:
# Evaluate matrix of data 
from sklearn.metrics import confusion_matrix,classification_report

conf_matrix1 = confusion_matrix(y_test, y_pred1)
conf_matrix2 = confusion_matrix(y_test, y_pred2)
conf_matrix3 = confusion_matrix(y_test, y_pred3)
print("The confusion matrix for decision tree is : ",conf_matrix1)
print("The confusion matrix for random forest is : ",conf_matrix2)
print("The confusion matrix for gradient boosting is : ",conf_matrix3)

print("Classification report of Decision tree:")
print(classification_report(y_test, y_pred1))
print("Classification report of random forest:")
print(classification_report(y_test, y_pred2))
print("Classification report of gradient boost:")
print(classification_report(y_test, y_pred3))


The accuracy score for decision tree is :  0.8959810874704491
The accuracy score for random forest is :  0.950354609929078
The accuracy score for gradient boosting is :  0.933806146572104
The confusion matrix for decision tree is :  [[52  4  0  0  0  0  0]
 [ 9 46  0  0  0  6  1]
 [ 0  0 72  4  0  0  2]
 [ 0  0  0 58  0  0  0]
 [ 0  0  0  0 63  0  0]
 [ 0  4  0  0  0 45  7]
 [ 0  0  2  0  0  5 43]]
The confusion matrix for random forest is :  [[56  0  0  0  0  0  0]
 [ 2 53  0  0  0  4  3]
 [ 0  0 74  3  0  0  1]
 [ 0  0  0 58  0  0  0]
 [ 0  0  0  0 63  0  0]
 [ 0  2  0  0  0 54  0]
 [ 0  0  3  0  0  3 44]]
The confusion matrix for gradient boosting is :  [[55  1  0  0  0  0  0]
 [ 4 53  0  0  0  3  2]
 [ 0  0 74  4  0  0  0]
 [ 0  0  0 58  0  0  0]
 [ 0  0  0  0 63  0  0]
 [ 0  4  0  0  0 48  4]
 [ 0  0  3  0  0  3 44]]
Classification report of Decision tree:
              precision    recall  f1-score   support

           0       0.85      0.93      0.89        56
           1     